
[workspace]
resolver = "3"
members = ["codegen-test", "codegen-rust", "parser", "wire", "wire-derive"]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Nova King <technobaboo@proton.me>"]
license = "MIT"

[workspace.dependencies]
strong-ipc = "0.1.0"

[workspace.dependencies.gluon-ipc-codegen]
version = "0.1.0"
path = "./codegen-rust"

[workspace.dependencies.gluon-ipc-parser]
version = "0.1.0"
path = "./parser"

[workspace.dependencies.gluon-ipc]
version = "0.1.0"
path = "./wire"

[workspace.dependencies.gluon-ipc-derive]
version = "0.1.0"
path = "./wire-derive"
