[package]
name = "gluon-ipc-derive"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Derive macro for gluon-ipc handlers"

[features]
tracing = []

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = { version = "2", features = ["derive"] }
